variables:
  CDP_IMAGE: ouestfrance/cdp:latest
  NODE_IMAGE: matthieupresse/php7-node14:latest # CF ./utils/Dockerfile-build-cdp

stages:
  - build
  - check
  - package
  - deploy

build:
  image: $NODE_IMAGE
  stage: build
  script:
    - yarn install
    - npx gulp html
    - npm run build-storybook
  artifacts:
    paths:
      - dist
    expire_in: 1day
  only:
    - branches
  tags:
    - int

checknpublish:
  image: $NODE_IMAGE
  stage: check
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - echo "$SSH_PRIVATE_KEY"
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "Host *.upload.akamai.com" > ~/.ssh/config
    - echo "HostKeyAlgorithms +ssh-dss" >> ~/.ssh/config
    - echo "PubkeyAcceptedKeyTypes +ssh-dss" >> ~/.ssh/config
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" >> ~/.ssh/config'
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - echo ${NPM_TOKEN}
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ./.npmrc
  script:
    - yarn install
    - npx gulp clean
    - npx gulp make-prod-assets
    - npm run checknpublish
  only:
    - master
  tags:
    - int

package_review:
  image: $CDP_IMAGE
  stage: package
  script:
    - cdp docker --image-tag-branch-name --use-gitlab-registry
  dependencies:
    - build
  only:
    - branches
  except:
    - master
    - develop
  tags:
    - int

package_staging:
  image: $CDP_IMAGE
  stage: package
  script:
    - cdp docker --image-tag-branch-name --use-aws-ecr
  dependencies:
    - build
  only:
    - master
    - develop
  tags:
    - int

deploy_review:
  image: $CDP_IMAGE
  stage: deploy
  script:
    - cdp k8s --internal-port=80 --use-gitlab-registry --namespace-project-branch-name --image-tag-branch-name --delete-labels=120 --create-default-helm --image-pull-secret
  environment:
    name: review/$CI_COMMIT_REF_NAME
  only:
    - branches
  except:
    - master
    - develop
  tags:
    - int

deploy_staging:
  image: $CDP_IMAGE
  stage: deploy
  script:
    - cdp k8s --internal-port=80 --use-aws-ecr --namespace-project-name --image-tag-branch-name --create-default-helm --image-pull-secret
  environment:
    name: review/$CI_COMMIT_REF_NAME
  only:
    - develop
  tags:
    - staging

deploy_prod:
  image: $CDP_IMAGE
  stage: deploy
  script:
    - cdp k8s --internal-port=80 --use-aws-ecr --namespace-project-name --image-tag-branch-name --create-default-helm --image-pull-secret
  environment:
    name: review/$CI_COMMIT_REF_NAME
  only:
    - master
  tags:
    - prod

